## Teste de Hipóteses

### Bibliotecas

In [1]:
# Libs
import math as mt
import numpy as np
from scipy.stats import norm

### Base de Dados

In [2]:
# Dados
dados_originais = np.array(
    [
        126. , 129.5, 133. , 133. , 136.5, 136.5, 140. , 140. , 140. ,
        140. , 143.5, 143.5, 143.5, 143.5, 143.5, 143.5, 147. , 147. ,
        147. , 147. , 147. , 147. , 147. , 150.5, 150.5, 150.5, 150.5,
        150.5, 150.5, 150.5, 150.5, 154. , 154. , 154. , 154. , 154. ,
        154. , 154. , 154. , 154. , 157.5, 157.5, 157.5, 157.5, 157.5,
        157.5, 157.5, 157.5, 157.5, 157.5, 161. , 161. , 161. , 161. ,
        161. , 161. , 161. , 161. , 161. , 161. , 164.5, 164.5, 164.5,
        164.5, 164.5, 164.5, 164.5, 164.5, 164.5, 168. , 168. , 168. ,
        168. , 168. , 168. , 168. , 168. , 171.5, 171.5, 171.5, 171.5,
        171.5, 171.5, 171.5, 175. , 175. , 175. , 175. , 175. , 175. ,
        178.5, 178.5, 178.5, 178.5, 182. , 182. , 185.5, 185.5, 189.,
        192.5
    ]
)

In [3]:
# Hipótese nula e média
H0_media = np.mean(dados_originais)
H0_media

159.25

In [4]:
# Hipótese nula e desvio padrão
H0_dp = np.std(dados_originais)
H0_dp

13.65

In [5]:
# Gerando novos dados
dados_novos = dados_originais * 1.03
dados_novos

array([129.78 , 133.385, 136.99 , 136.99 , 140.595, 140.595, 144.2  ,
       144.2  , 144.2  , 144.2  , 147.805, 147.805, 147.805, 147.805,
       147.805, 147.805, 151.41 , 151.41 , 151.41 , 151.41 , 151.41 ,
       151.41 , 151.41 , 155.015, 155.015, 155.015, 155.015, 155.015,
       155.015, 155.015, 155.015, 158.62 , 158.62 , 158.62 , 158.62 ,
       158.62 , 158.62 , 158.62 , 158.62 , 158.62 , 162.225, 162.225,
       162.225, 162.225, 162.225, 162.225, 162.225, 162.225, 162.225,
       162.225, 165.83 , 165.83 , 165.83 , 165.83 , 165.83 , 165.83 ,
       165.83 , 165.83 , 165.83 , 165.83 , 169.435, 169.435, 169.435,
       169.435, 169.435, 169.435, 169.435, 169.435, 169.435, 173.04 ,
       173.04 , 173.04 , 173.04 , 173.04 , 173.04 , 173.04 , 173.04 ,
       176.645, 176.645, 176.645, 176.645, 176.645, 176.645, 176.645,
       180.25 , 180.25 , 180.25 , 180.25 , 180.25 , 180.25 , 183.855,
       183.855, 183.855, 183.855, 187.46 , 187.46 , 191.065, 191.065,
       194.67 , 198.

In [6]:
# Média da hipótese alternativa
H1_media = np.mean(dados_novos)
H1_media

164.0275

In [7]:
# desvio padrão da hipótese alternativa
H1_dp = np.std(dados_novos)
H1_dp

14.0595

In [8]:
# Quantidade de elementos
H1_n = len(dados_novos)
H1_n

100

In [9]:
# Nível de confiança 
alpha = 0.05

### Teste de Hipótese Z

#### Teste Manual

In [10]:
# Variável Z
Z = (H1_media - H0_media) / (H1_dp / mt.sqrt(H1_n))
Z

3.398058252427187

In [11]:
# Visualizando a probabilidade
norm.cdf(Z), norm.ppf(0.9996606701617486)

(0.9996606701617486, 3.3980582524271936)

In [12]:
# Refazendo a variável Z
Z = norm.cdf(Z)
Z

0.9996606701617486

In [13]:
# Valor p
p = 1 - Z
p

0.00033932983825135654

In [14]:
# Verificando qual hipótese foi rejeitada 
if p < alpha:
    print('Hipótese nula rejeitada')
else:
    print('Hipótese alternativa rejeitada')

Hipótese nula rejeitada


### Teste com o statsmodels
- https://www.statsmodels.org/devel/generated/statsmodels.stats.weightstats.ztest.html

#### Biblioteca

In [15]:
# Libs
from statsmodels.stats.weightstats import ztest

In [16]:
# Teste Z
_, p = ztest(
    dados_originais, dados_novos,
    value=H1_media - H0_media,
    alternative='larger'
)

In [17]:
# Visualizando o valor de p
p

0.9999993877283934

### Teste qui quadrado
- https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.chi2_contingency.html

#### Biblioteca

In [18]:
# Lib
from scipy.stats import chi2_contingency

In [19]:
# Tabela de Dados
# tabela = np.array([[30, 20], [22, 28]])
tabela = np.array([[45, 5], [5, 45]])

In [20]:
# Tamanho 
tabela.shape

(2, 2)

In [21]:
# valor de p
_, p, _, _ = chi2_contingency(tabela)
p

6.190717543917382e-15

In [22]:
# Testando a Hipótese
alpha = 0.05
if p <= alpha:
    print('Hipótese nula rejeitada')
else:
    print('Hipótese alternativa rejeitada')

Hipótese nula rejeitada


### Seleção de atributos com testes de hipóteses - univariate SelectFdr
Testes estatísticos univariados são aqueles que envolvem uma variável dependente, por exemplo, teste t ou teste z para comparação de médias

- Documentação: https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.SelectFpr.html#sklearn.feature_selection.SelectFpr

- False discovery rate: https://en.wikipedia.org/wiki/False_discovery_rate

Proporção esperada de erros do tipo I. Um erro do tipo I é quando a hipótese nula é rejeitada incorretamente, ou seja, é obtido um falso positivo

- Erro I: https://www.statisticshowto.datasciencecentral.com/probability-and-statistics/statistics-definitions/type-i-error-type-ii-error-decision/

#### Bibliotecas

In [23]:
# Lib
import pandas as pd
from sklearn.feature_selection import SelectFdr
from sklearn.feature_selection import chi2
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

#### Base de Dados

In [24]:
# Dados
ds = pd.read_csv('./data/ad.data', header=None)
ds.head()

0     1       2     3     4     5     6     7     8     9     ...  1549  \
0   125   125  1.0000     1     0     0     0     0     0     0  ...     0   
1    57   468  8.2105     1     0     0     0     0     0     0  ...     0   
2    33   230  6.9696     1     0     0     0     0     0     0  ...     0   
3    60   468  7.8000     1     0     0     0     0     0     0  ...     0   
4    60   468  7.8000     1     0     0     0     0     0     0  ...     0   

   1550  1551  1552  1553  1554  1555  1556  1557  1558  
0     0     0     0     0     0     0     0     0   ad.  
1     0     0     0     0     0     0     0     0   ad.  
2     0     0     0     0     0     0     0     0   ad.  
3     0     0     0     0     0     0     0     0   ad.  
4     0     0     0     0     0     0     0     0   ad.  

[5 rows x 1559 columns]

In [25]:
# Tamanho 
ds.shape

(3279, 1559)

In [26]:
# Dividindo em previsores e classes
X = ds.iloc[:, 0:1558].values
y = ds.iloc[:, 1558].values
y

array(['ad.', 'ad.', 'ad.', ..., 'nonad.', 'nonad.', 'nonad.'],
      dtype=object)

In [27]:
# Contando os valores únicos
np.unique(y, return_counts=True)

(array(['ad.', 'nonad.'], dtype=object), array([ 459, 2820], dtype=int64))

#### Sem seleção de Atributos

In [28]:
# Criando e Treinado o modelo
naive1 = GaussianNB()
naive1.fit(X, y)
previsoes1 = naive1.predict(X)
accuracy_score(y, previsoes1)

0.7813357731015553

#### Seleção de atributos com Qui Quadrado

In [29]:
# Criando nova seleção
selecao = SelectFdr(chi2, alpha=0.01)
X_novo = selecao.fit_transform(X, y)

In [30]:
# Tamanho
X.shape, X_novo.shape

((3279, 1558), (3279, 433))

In [31]:
# Valor de p
selecao.pvalues_, len(selecao.pvalues_)

(array([2.14710304e-268, 0.00000000e+000, 8.98165813e-150, ...,
        6.03353380e-041, 5.63437216e-012, 9.37945775e-002]),
 1558)

In [32]:
# Seleção de valores menores ou igual ao alpha
np.sum(selecao.pvalues_ <= 0.01)

476

In [33]:
# Visualizando os valores 
colunas = selecao.get_support()
colunas

array([ True,  True,  True, ...,  True,  True, False])

In [34]:
# Selecionado as coluna com valores True
indices = np.where(colunas == True)
indices

(array([   0,    1,    2,    9,   11,   14,   20,   21,   26,   31,   34,
          36,   49,   58,   59,   64,   65,   69,   70,   86,   91,   95,
          96,  102,  104,  106,  113,  133,  134,  139,  155,  158,  163,
         167,  172,  175,  180,  181,  183,  185,  186,  189,  190,  192,
         193,  224,  242,  246,  248,  249,  251,  259,  264,  265,  266,
         267,  268,  269,  270,  274,  276,  278,  287,  290,  293,  304,
         307,  310,  312,  317,  321,  329,  330,  336,  341,  345,  346,
         350,  351,  355,  356,  357,  359,  366,  367,  370,  372,  381,
         386,  388,  389,  398,  405,  418,  420,  426,  427,  429,  430,
         432,  435,  440,  455,  457,  460,  465,  470,  472,  477,  478,
         482,  508,  511,  518,  528,  532,  533,  540,  542,  548,  551,
         556,  572,  573,  574,  576,  586,  622,  625,  627,  638,  643,
         648,  653,  658,  661,  663,  666,  683,  688,  694,  703,  704,
         709,  711,  720,  723,  729, 

In [35]:
# Criando e Treinado o novo modelo com a seleção
naive2 = GaussianNB()
naive2.fit(X_novo, y)
previsoes2 = naive2.predict(X_novo)
accuracy_score(y, previsoes2)

0.970722781335773