## Previsão de Probabilidades em Machine Learning

In [1]:
# Biblioteca 
import pandas as pd
import numpy as np
from sklearn.naive_bayes import GaussianNB

In [2]:
# Base de dados
dataset = pd.read_csv('.././Labs/Amostragem/credit_data.csv')
dataset.dropna(inplace=True)
dataset.head()

i#clientid        income        age         loan  c#default
0           1  66155.925095  59.017015  8106.532131          0
1           2  34415.153966  48.117153  6564.745018          0
2           3  57317.170063  63.108049  8020.953296          0
3           4  42709.534201  45.751972  6103.642260          0
4           5  66952.688845  18.584336  8770.099235          1

In [3]:
# Variáveis previsoras 
X = dataset.iloc[:,1:4].values
X

array([[6.61559251e+04, 5.90170151e+01, 8.10653213e+03],
       [3.44151540e+04, 4.81171531e+01, 6.56474502e+03],
       [5.73171701e+04, 6.31080495e+01, 8.02095330e+03],
       ...,
       [4.43114493e+04, 2.80171669e+01, 5.52278669e+03],
       [4.37560566e+04, 6.39717958e+01, 1.62272260e+03],
       [6.94365796e+04, 5.61526170e+01, 7.37883360e+03]])

In [4]:
# Variáveis de classes
y = dataset.iloc[:,4].values
y

array([0, 0, 0, ..., 1, 0, 0], dtype=int64)

In [5]:
# Criando e treinado o modelo
naive_bayes = GaussianNB()
naive_bayes.fit(X, y)

GaussianNB()

In [6]:
# Tamanho
X[0], X[0].shape

(array([6.61559251e+04, 5.90170151e+01, 8.10653213e+03]), (3,))

In [7]:
# Redimensionando 
novo = X[0].reshape(1,-1)
novo, novo.shape

(array([[6.61559251e+04, 5.90170151e+01, 8.10653213e+03]]), (1, 3))

In [8]:
# Predição 
naive_bayes.predict(novo)

array([0], dtype=int64)

In [9]:
# Predição de probabilidade
previsao = naive_bayes.predict_proba(novo)
previsao

array([[1.00000000e+00, 2.03924534e-10]])

In [10]:
# Valor máximo
np.argmax(previsao)

0