## Exercícios
- Calcule a variância para os atributos income, age e loan e aplique o método de seleção Low Variance

- Faça um teste do accuracy utilizando o algoritmo Naïve Bayes, sem seleção de atributos e com seleção de atributos

In [1]:
# Bibliotecas
import math
import pandas as pd
import numpy as np
from sklearn.feature_selection import VarianceThreshold

In [2]:
# Dataset
ds = pd.read_csv('../Amostragem/credit_data.csv')
ds.head()

i#clientid        income        age         loan  c#default
0           1  66155.925095  59.017015  8106.532131          0
1           2  34415.153966  48.117153  6564.745018          0
2           3  57317.170063  63.108049  8020.953296          0
3           4  42709.534201  45.751972  6103.642260          0
4           5  66952.688845  18.584336  8770.099235          1

In [3]:
# Visualizando a info
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   i#clientid  2000 non-null   int64  
 1   income      2000 non-null   float64
 2   age         1997 non-null   float64
 3   loan        2000 non-null   float64
 4   c#default   2000 non-null   int64  
dtypes: float64(3), int64(2)
memory usage: 78.2 KB


In [4]:
# Limpando as NAs
ds.dropna(inplace=True)
ds.shape

(1997, 5)

In [5]:
# Selecionado as coluna income
X = ds.iloc[:, 1:4].values
X

array([[6.61559251e+04, 5.90170151e+01, 8.10653213e+03],
       [3.44151540e+04, 4.81171531e+01, 6.56474502e+03],
       [5.73171701e+04, 6.31080495e+01, 8.02095330e+03],
       ...,
       [4.43114493e+04, 2.80171669e+01, 5.52278669e+03],
       [4.37560566e+04, 6.39717958e+01, 1.62272260e+03],
       [6.94365796e+04, 5.61526170e+01, 7.37883360e+03]])

In [6]:
# A Variância das colunas income, age e loan
np.var(ds['income']), np.var(ds['age']), np.var(ds['loan'])

(205106624.4066086, 185.5332154337263, 9278295.83293169)

In [7]:
# Criando a seleção
selecao = VarianceThreshold(threshold=4)
x_novo = selecao.fit_transform(X)

In [8]:
# Visualizando o X_novo e o tamanho
x_novo, x_novo.shape

(array([[6.61559251e+04, 5.90170151e+01, 8.10653213e+03],
        [3.44151540e+04, 4.81171531e+01, 6.56474502e+03],
        [5.73171701e+04, 6.31080495e+01, 8.02095330e+03],
        ...,
        [4.43114493e+04, 2.80171669e+01, 5.52278669e+03],
        [4.37560566e+04, 6.39717958e+01, 1.62272260e+03],
        [6.94365796e+04, 5.61526170e+01, 7.37883360e+03]]),
 (1997, 3))

### Correção com o tutor

In [9]:
# Criando a classe
y = ds.iloc[:, 4].values
y

array([0, 0, 0, ..., 1, 0, 0], dtype=int64)

In [10]:
# Importação da bibliotecas e normalizados
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X = scaler.fit_transform(X)
X

array([[0.9231759 , 0.95743135, 0.58883739],
       [0.28812165, 0.86378597, 0.47682695],
       [0.74633429, 0.99257918, 0.58262011],
       ...,
       [0.48612202, 0.69109837, 0.40112895],
       [0.47500998, 1.        , 0.1177903 ],
       [0.98881367, 0.93282208, 0.53597028]])

In [11]:
# Visualizando as Variância 
np.var(X[:, 0]), np.var(X[:, 1]), np.var(X[:, 2])

(0.08210439343522123, 0.013694697910033629, 0.04897070767524547)

In [12]:
# Criando a seleção
selecao = VarianceThreshold(threshold=0.02)
x_novo = selecao.fit_transform(X)
x_novo

array([[0.9231759 , 0.58883739],
       [0.28812165, 0.47682695],
       [0.74633429, 0.58262011],
       ...,
       [0.48612202, 0.40112895],
       [0.47500998, 0.1177903 ],
       [0.98881367, 0.53597028]])

In [13]:
# Criando o modelo e o trenamento sem a variância 
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
n_sem_selecao = GaussianNB()
n_sem_selecao.fit(X, y)
previsoes = n_sem_selecao.predict(X)
accuracy_score(previsoes, y)

0.9253880821231848

In [14]:
# Criando o modelo e o trenamento com a variância 
n_com_selecao = GaussianNB()
n_com_selecao.fit(x_novo, y)
previsoes = n_com_selecao.predict(x_novo)
accuracy_score(previsoes, y)

0.8472709063595393